language: php

php:
  - 5.3
  - 5.4

before_script:
    - git checkout master
    - php bin/vendors install
    - php bin/prepare-test-env

script: phpunit -c app/

branches:
  only:
    - master

